#!/usr/bin/env bash
# Bake the built SPA into firmware/plotter/web_assets.h.
#
# Source lives at /web (Vite + Svelte). The plugin `vite-plugin-singlefile`
# inlines all JS/CSS into one HTML, so we only embed one file.
#
# Usage (from anywhere in the repo):
#
#     ./scripts/build_web.sh
#
#     ( cd web && npm run build ) && ./scripts/build_web.sh
#
set -euo pipefail

# Resolve repo root regardless of where this is invoked from.
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$REPO_ROOT/web/dist/index.html"
OUT="$REPO_ROOT/firmware/plotter/web_assets.h"

if [ ! -f "$SRC" ]; then
  echo "ERROR: $SRC not found. Build the SPA first:" >&2
  echo "  cd web && npm install && npm run build" >&2
  exit 1
fi

if grep -q ')WEBASSET"' "$SRC"; then
  echo "ERROR: $SRC contains the raw-string terminator )WEBASSET\"" >&2
  exit 1
fi

cat > "$OUT" <<'EOF'
// Auto-generated by scripts/build_web.sh — do not edit by hand. Gitignored.
// Source: /web (Vite + Svelte SPA, single-file build via vite-plugin-singlefile).
#pragma once
#include <Arduino.h>

namespace web_assets {

EOF

printf 'const char INDEX_HTML[] PROGMEM = R"WEBASSET(\n' >> "$OUT"
cat "$SRC" >> "$OUT"
printf ')WEBASSET";\n\n' >> "$OUT"

cat >> "$OUT" <<'EOF'
}  // namespace web_assets
EOF

bytes=$(wc -c < "$SRC" | tr -d ' ')
echo "Wrote $OUT ($bytes bytes inline)"
